Remove unused private member 'step_' from nlb7 class (#1447)
In the nlb0 and nlb3 classes step_ is used to support the command
line option multi-cl.  This option is not present in nlb7.

Fixes the clang error.

.../opae-sdk/tools/extra/fpgadiag/nlb7.h:79:14: error: private field 'step_' is not used [-Werror,-Wunused-private-field]
    uint32_t step_;
             ^