Trix/master/sa option (#1446)
* Add a trivial virtual destructor to option class

Because the option class has virtual functions, it needs a
virutal destructor.

Fixes the clang + libc++  error

.../include/c++/v1/memory:2363:5: error: delete called on non-final 'intel::utils::typed_option<bool>' that has virtual functions but non-virtual destructor [-Werror,-Wdelete-non-abstract-non-virtual-dtor]
    delete __ptr;

* Add override specifier to several virtual functions in the nlb7 class

These additions are consistent with the nlb3 and nlb0 classes

Fixes the clang++ error and other similar errors

.../opae-sdk/tools/extra/fpgadiag/nlb7.h:53:40: error: 'get_options' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
    virtual intel::utils::option_map & get_options()          { return options_; }
                                       ^

* Update option.h

Co-authored-by: Tim Whisonant <tim.whisonant@intel.com>
Co-authored-by: Ananda Ravuri <33236856+anandaravuri@users.noreply.github.com>