Clang (#1943)
* remove unused private memebers

When building with clang 13, there is this representive error

  eth_group.h:138:6: error: private field 'container' is not used

Several other members are also unused.
So remove them.

Signed-off-by: Tom Rix <trix@redhat.com>

* fix usage of std::initialize_list

Building with clang fails with this error

  afu_test.h:242:35: error: array backing local initializer list
  'sinks' will be destroyed at the end of the full-expression
  [-Werror,-Wdangling]
    spdlog::sinks_init_list sinks({console_sink, file_sink});
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~

sinks_init_list is really
using sinks_init_list = std::initializer_list<sink_ptr>;

Because 'sinks' is only used in the constructor of logger,
remove the use of the variable 'sinks' and call sinks_init_list()
as a parameter of the constructor.

Signed-off-by: Tom Rix <trix@redhat.com>

* add missing override specifiers

Building with clang fails with this representative message

  host_exerciser_lpbk.h:45:23: error: 'name' overrides a member
  function but is not marked 'override'
    virtual const char *name() const

Add the overrides.

Signed-off-by: Tom Rix <trix@redhat.com>

* remove dead store

clang static analysis reports this error.

mmlink_connection.cpp:118:2: warning: Value stored to 'i' is never read
        i = 0;
        ^   ~

i is initialized before use in the for-loop, so remove this line.

Signed-off-by: Tom Rix <trix@redhat.com>

Co-authored-by: Rodrigo Rojo <rodrigo.rojo@intel.com>